[package]
name = "stokes-browser"
version = "0.1.0"
edition = "2024"

[dependencies]
glutin = "0.32.3"
glutin-winit = "0.5.0"
gl = "0.14.0"
skia-safe = { version = "0.90.0", features = ["gpu", "gl"] }
#winit = { version = "0.30.12", features = ["wayland"] }
image = "0.25.8"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
futures = "0.3"
curl = "0.4"
html5ever = "0.36.1"
markup5ever_rcdom = "0.36.0+unofficial"
resvg = "0.45.1"
usvg = "0.45.1"
tiny-skia = "0.11.4"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
#boa_engine = "0.20.0"
#boa_gc = "0.20.0"
base64 = "0.22"
stacker = "0.1"
serde_json = "1.0.145"
shared_memory = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "2.0.1"
parking_lot = "0.12"
uds_windows = "1.1.0"
rfd = "0.15"
url = "2"
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "fff4ea6e71e4f6ec29d0ea560a77545ad611470a" }
slab = "0.4.11"
markup5ever = "0.36.1"
parley = "0.6.0"
euclid = "0.22.11"
bitflags = "2.10.0"
atomic_refcell = "0.1.13"
skrifa = "0.39.0"
kurbo = "0.12.0"
bytes = "1.10.1"
tracing = "0.1.41"
wuff = "0.2.1"
hashbrown = "0.16.0"
peniko = "0.5.0"
anyrender = "0.6.2"
color = "0.3.2"
html-escape = "0.2.13"

# Stylo
stylo = "0.9.0"
stylo_traits = "0.9.0"
stylo_atoms = "0.9.0"
stylo_config = "0.9.0"
stylo_dom = "0.9.0"
selectors = "0.33.0"

# Blitz
blitz-traits = { git = "https://github.com/DioxusLabs/blitz", rev = "b8b88a5d" }
blitz-net = { git = "https://github.com/DioxusLabs/blitz", rev = "b8b88a5d" }
stylo_taffy = { git = "https://github.com/DioxusLabs/blitz", rev = "b8b88a5d", features = ["floats"] }

[dependencies.winit]
git = "https://github.com/Treetrain1/winit.git"
default-features = true

[patch.crates-io]
winit = { git = "https://github.com/Treetrain1/winit.git" }

[dependencies.boa_engine]
git = "https://github.com/boa-dev/boa.git"
default-features = true

[dependencies.boa_gc]
git = "https://github.com/boa-dev/boa.git"
default-features = true