[package]
name = "stokes-browser"
version = "0.1.0"
edition = "2024"

[dependencies]
glutin = "0.32.3"
glutin-winit = "0.5.0"
gl = "0.14.0"
skia-safe = { version = "0.93.0", features = ["gpu", "gl"] }
#winit = { version = "0.30.12", features = ["wayland"] }
image = "0.25.8"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
futures = "0.3"
curl = "0.4"
html5ever = "0.37.1"
#markup5ever_rcdom = "0.36.0+unofficial"
markup5ever_rcdom = { git = "https://github.com/EthanRStokes/html5ever", rev = "f06da2b" }
usvg = "0.46.0"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
mozjs = "0.15.0"
#mozjs = { git = "https://github.com/servo/mozjs.git", rev = "125b5ab" }
base64 = "0.22"
stacker = "0.1"
serde_json = "1.0.145"
shared_memory = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "2.0.1"
uds_windows = "1.1.0"
rfd = "0.17.2"
url = "2"
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "25759dad44d8350743a4e866fee54962f996895a" }
slab = "0.4.11"
markup5ever = "0.37.1"
parley = { git = "https://github.com/linebender/parley", rev = "37aa8ab7103e9da89eea22899902016ce20739f2" }
euclid = "0.22.13"
bitflags = "2.10.0"
atomic_refcell = "0.1.13"
skrifa = "0.40.0"
kurbo = "0.13.0"
bytes = "1.11.0"
tracing = "0.1.44"
hashbrown = "0.16.1"
peniko = "0.6.0"
anyrender = "0.7.0"
color = "0.3.2"
html-escape = "0.2.13"
lazy_static = "1.5.0"
hirofa_utils = "0.7.4"

# Stylo
stylo = "0.12.0"
stylo_traits = "0.12.0"
stylo_atoms = "0.12.0"
stylo_config = "0.12.0"
stylo_dom = "0.12.0"
selectors = "0.35.0"

# Blitz
blitz-traits = { git = "https://github.com/DioxusLabs/blitz", rev = "eeaa9938fac918bd07e5a30472d0f4a44e8ffa31" }
blitz-net = { git = "https://github.com/DioxusLabs/blitz", rev = "eeaa9938fac918bd07e5a30472d0f4a44e8ffa31" }
stylo_taffy = { git = "https://github.com/DioxusLabs/blitz", rev = "eeaa9938fac918bd07e5a30472d0f4a44e8ffa31", features = ["floats"] }
log = "0.4.28"
wuff = "0.2.3"
dirs = "6.0"
libc = "0.2.178"

[dependencies.winit]
git = "https://github.com/Treetrain1/winit.git"
default-features = true

[patch.crates-io]
winit = { git = "https://github.com/Treetrain1/winit.git" }